---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: fileshelter
  namespace: file_drop
  labels:
    deployment: fileshelter
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: file_drop
  template:
    metadata:
      labels:
        deployment: file_drop
    spec:
      volumes:
      - name: files
        gcePersistentDisk:
          pdName: filestore
          fsType: ext4
      containers:
      - name: fileshelter
        image: dylanratcliffe/fileshelter:latest
        ports:
        - name: fileshelter
          hostPort: 5091
          containerPort: 5091
          protocol: TCP
        resources: {}
        volumeMounts:
        - name: files
          mountPath: "/var/fileshelter"
        imagePullPolicy: Always
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  revisionHistoryLimit: 1
